language: php

sudo: false

php:
  - 7.0

env:
  matrix:
    - DB=mysql db_dsn='mysql://root@127.0.0.1/cakephp_test'
    - DB=pgsql db_dsn='postgres://postgres@127.0.0.1/cakephp_test'

matrix:
  include:
    - php: 7.0
      env: DEFAULT=1

    - php: 7.0
      env: PHPCS=1 DEFAULT=0

    - php: 7.0
      env: PHPSTAN=1 DEFAULT=0

    - php: 7.0
      env: COVERALLS=1 DEFAULT=0 DB=mysql db_dsn='mysql://root@127.0.0.1/cakephp_test'

  fast_finish: true

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

  - if [[ $DB = 'mysql' ]]; then mysql -u root -e 'CREATE DATABASE cakephp_test;'; fi
  - if [[ $DB = 'pgsql' ]]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi
  - if [[ $COVERALLS = 1 ]]; then mkdir -p build/logs; fi

script:
#  - if [[ $DEFAULT = 1 ]]; then vendor/bin/phpunit; fi
  - if [[ $COVERALLS = 1 ]]; then php vendor/bin/coveralls -c .coveralls.yml -v; fi
  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./config; fi
  - if [[ $PHPSTAN = 1 ]]; then composer require --dev phpstan/phpstan:^0.8; fi
  - if [[ $PHPSTAN = 1 ]]; then vendor/bin/phpstan analyse -l 3 src; fi

notifications:
  email: false
